//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IdAction { get; set; }
        public string Action { get; set; }
        public int IdDocument { get; set; }
        public System.DateTime TimeOfChange { get; set; }
        public string PreviousValue { get; set; }
        public string NewValue { get; set; }
    }
}
