//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IfDocumentIsExternal
    {
        public int IdIDIE { get; set; }
        public int IdDocument { get; set; }
        public string IncomingNumber { get; set; }
        public string OutgoingNumber { get; set; }
        public string FromWhere_Or_WhereTo { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
