//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewInternalDocuments
    {
        public int IdDocument { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Creator { get; set; }
        public int IdPerson { get; set; }
        public string TypeName { get; set; }
        public string ImportanceName { get; set; }
        public string PeriodOfExecution { get; set; }
        public string DepartmentName { get; set; }
        public int IdDepartment { get; set; }
        public int IdDocumentType { get; set; }
        public int IdImportance { get; set; }
    }
}
