//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPersons
    {
        public int IdPerson { get; set; }
        public string Person { get; set; }
        public string PositionName { get; set; }
        public string DepartmentName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfHiring { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<byte> Age { get; set; }
        public int IdDepartment { get; set; }
        public int IdPosition { get; set; }
    }
}
